### ISSUE TITLE
V7 web blocks throws exception when macro is inserted into RTE

### ISSUE THREAD

**Issue by bowserm** [base33/Web-Blocks#10]
I'm experiencing this on web blocks 4.0.1

When I add macros to rich text editors on blocks. I get exceptions like this when I try to add the block to a page.

```
Block Exception:System.InvalidOperationException: Cannot render a macro when there is no current PublishedContentRequest.
   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.&lt;&gt;c__DisplayClass7.&lt;RenderRteMacros&gt;b__1(String macroAlias, Dictionary`2 macroAttributes)
   at Umbraco.Core.Macros.MacroTagParser.ParseMacros(String text, Action`1 textFoundCallback, Action`2 macroFoundCallback)
   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.RenderRteMacros(String source, Boolean preview)
   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.ConvertDataToSource(PublishedPropertyType propertyType, Object source, Boolean preview)
   at WebBlocks.Utilities.Umbraco.ContentPropertyWrapper.get_Value()
   at Umbraco.Web.Models.DynamicPublishedContent.TryGetUserProperty(GetMemberBinder binder)
   at Umbraco.Web.Models.DynamicPublishedContent.&lt;&gt;c__DisplayClass9.&lt;TryGetMember&gt;b__6(Func`2 m)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Umbraco.Web.Models.DynamicPublishedContent.TryGetMember(GetMemberBinder binder, Object&amp; result)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ASP._Page_Views_Partials_ImageTextBlock_cshtml.Execute() in c:\ProWorks\mysite\mysite_v7_git\src\mysite\Views\Partials\ImageTextBlock.cshtml:line 30
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at WebBlocks.Views.RenderingEngines.PartialViewRenderingEngine.Render(HtmlHelper html)
```

**Comment by bowserm** [comment]
Ah. I just learned that this error only displays in the backoffice. If I save and publish the node, the block displays fine on the front end of the site. Also, if I click "Save and Publish" and then I click "Rerender Builder", the error will disappear from the backoffice as well. This is an ok workaround for devs, but it will really scare our non-technical content editors.

**Comment by base33** [comment]
Hey Mark,

Really sorry for the late reply.  Things have been extremely busy.  I am beginning the development of the next release of Web Blocks, which will hopefully include this feature and the ability to have a controller to handle rendering blocks.

If you or any of your colleagues have any features you'd like to see, add an issue into GitHub.

I will be uploading the source code to GitHub tonight, so you can get access to the source code here from tomorrow.

Thanks for bringing this feature to my attention.

Craig
